[tool.black]
line-length = 160
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | assets
)/
'''

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_no_return = true
warn_return_any = false
warn_unused_ignores = false

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[tool.pyright]
include = ["sources"]
reportMissingImports = true
reportMissingTypeStubs = false
reportInvalidTypeForm = "none"
